### ISSUE TITLE
Akadora hidden in ankan

### ISSUE THREAD

**Issue by John-Johns0n** [Varantha/Mahjong-ScoringTrainer#28]
**Describe the bug**
1 extra han coming from akadora was part of the score total, but it was not visible on screen (presumably hidden in the closed kan).

**Expected behaviour**
Any akadora in a closed kan should be shown as one of the two visible (middle) tiles.

**Hand ID**
2011010116gm-00a9-0000-333c7fb69

**Screenshots**
[Ankan akadora bug](https://user-images.githubusercontent.com/84598043/220195790-4ed62355-252e-406c-a171-e552349b3a92.png)

Another, unrelated note: Earlier I had a hand with the yaku `sanshoku doujun`, which was misspelled as `sanshokudoujin` in the han tooltip: [proof](https://cdn.discordapp.com/attachments/1014189878700945471/1077335771511521481/image.png).

**Comment by Varantha** [comment]
Hi there @John-Johns0n, thanks for logging an issue! 😄(In fact the first issue not logged by me)

However, I'm not 100% sure about this one. Part of my motivation for this trainer is to mimic the difficulty of scoring Mahjong games as closely as possible. 

For IRL MJ games (and Tenhou games too I think) it is possible that the red five could be hidden as one of the flipped tiles in a closed kan. In this case you will just need to go off the knowledge that a kan of 5s will always contain 1 red five no matter what. 

Making it so that the red five is always shown as one of the centre tiles may make it easier than it would be normally, which is something I want to avoid. (Outside of making a specific "easy mode" which helps you out more than usual)

Hopefully that all makes sense. 

For the issue regarding the name though, I'll start a PR to get that fixed. Thanks for raising that as well.

**Comment by Varantha** [comment]
Fixed "sanshoku doujun" name.

But unlikely to change akadoras being hidden within ankan, I believe it is more realistic to keep this in.

Feel free to log another issue if you believe this to be wrong.
