### ISSUE TITLE
Trying to scroll over the currently selected input field causes it to change the value

### ISSUE THREAD

**Issue by gameraccoon** [Varantha/Mahjong-ScoringTrainer#42]
**Describe the bug**
If a user tries to scroll the page (e.g. using the mouse scroll wheel or touchpad gesture) while the cursor is over the currently selected field, then the value in the field can change.

It sometimes results in accidentally changing the value without noticing it.

Reproduced on Firefox (haven't tried other browsers).

**Expected behaviour**
Scrolling over a field doesn't change the value in that field (it is fine if the page is not being scrolled in that case, just the fact of the value change is annoying).

**Hand ID**
Any hand

**Screenshots**
A short video
[Screencast from 2023-08-11 21-17-35.webm](https://github.com/Varantha/Mahjong-ScoringTrainer/assets/24990031/e9a2cc73-7ea7-426d-b959-f02ba0ebbc40)

**Comment by Varantha** [comment]
Hey @gameraccoon, 

Thanks for raising and sorry for the delay! I think this was so close to the other issue that I saw the notification and thought I'd already solved it. 

This is on me for trying to be fancy with the input type 😅 I've added something that should make it lose focus on scroll now, so that should make it scroll with the page at all times instead. 

However your setup is very different from mine - so please do test and confirm that's better for you now 🙂

**Comment by gameraccoon** [comment]
Yes, it works well now, thank you for the fix (and no worries, I don't expect people to fix bugs right away 😄)
