### ISSUE TITLE
A couple suggestions for making it efficient to use with just the keyboard

### ISSUE THREAD

**Issue by travv0** [Varantha/Mahjong-ScoringTrainer#45]
Just a couple minor enhancements that would help for those wanting to go through a bunch of hands at a quicker pace, but it would be nice if pressing Enter again after submitting your answers pulled up a new hand, and when a new hand was generated, it automatically focuses the han text input.

**Comment by Varantha** [comment]
Hi @travv0 
Thanks for the double suggestion!
I've made it so that it will focus the `New Hand` button after checking the answer (which is a bit of a hacky way to do it but it seems to work) so it should refresh the hand if you press enter again. 
Please give it a test and let me know if there are any issues with it.

**Comment by travv0** [comment]
Works perfectly, thanks!
